-- ============================================
-- MIGRACIÓN: Facturación Electrónica + Seguimiento
-- Valentina Niebles v2.1
-- Ejecuta este script en Supabase SQL Editor
-- ============================================

-- ============================================
-- 1. NUEVAS COLUMNAS EN ORDERS
-- ============================================
ALTER TABLE orders ADD COLUMN IF NOT EXISTS client_doc text default '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS cancellation_reason text default '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS cancellation_detail text default '';

-- ============================================
-- 2. TABLA: INVOICES (Facturas Electrónicas)
-- ============================================
create table if not exists invoices (
  id bigint generated by default as identity primary key,
  invoice_number text unique not null,
  order_id text not null references orders(id) on delete cascade,
  user_id uuid references profiles(id) on delete set null,

  -- Datos del cliente
  client_name text not null,
  client_email text not null,
  client_phone text default '',
  client_doc text default '',
  client_address text default '',

  -- Datos DIAN
  resolution_number text default '',
  resolution_date text default '',
  prefix text default 'FAC',
  consecutive integer not null,
  cufe text default '',
  qr_code text default '',

  -- Datos fiscales de la tienda
  store_nit text default '',
  store_name text default 'Valentina Niebles',
  store_regime text default 'comun',
  store_address text default '',
  store_phone text default '',
  store_email text default '',

  -- Detalle de productos y totales
  products jsonb not null,
  subtotal numeric(12,2) not null default 0,
  tax_rate numeric(5,2) not null default 19.00,
  tax_total numeric(12,2) not null default 0,
  discount numeric(12,2) not null default 0,
  total numeric(12,2) not null,

  -- Metadatos
  payment_method text default '',
  payment_status text default 'pendiente' check (payment_status in ('pendiente', 'pagado', 'anulado')),
  invoice_status text default 'emitida' check (invoice_status in ('emitida', 'anulada', 'reenviada')),
  pdf_url text default '',
  sent_at timestamp with time zone,
  created_at timestamp with time zone default now()
);

-- ============================================
-- 3. TABLA: ORDER_STATUS_LOG (Historial de cambios de estado)
-- ============================================
create table if not exists order_status_log (
  id bigint generated by default as identity primary key,
  order_id text not null references orders(id) on delete cascade,
  old_status text default '',
  new_status text not null,
  reason text default '',
  detail text default '',
  changed_by uuid references profiles(id) on delete set null,
  created_at timestamp with time zone default now()
);

-- ============================================
-- 4. ROW LEVEL SECURITY
-- ============================================

alter table invoices enable row level security;
alter table order_status_log enable row level security;

-- Invoices: users can see their own, admins can see all
create policy "Users can view own invoices"
  on invoices for select
  using (user_id = auth.uid());

create policy "Admins can view all invoices"
  on invoices for select
  using (public.is_admin());

create policy "Admins can insert invoices"
  on invoices for insert
  with check (public.is_admin());

create policy "Admins can update invoices"
  on invoices for update
  using (public.is_admin());

create policy "Admins can delete invoices"
  on invoices for delete
  using (public.is_admin());

-- Order Status Log: admins can see all, system can insert
create policy "Admins can view status log"
  on order_status_log for select
  using (public.is_admin());

create policy "Anyone can insert status log"
  on order_status_log for insert
  with check (true);

-- ============================================
-- 5. FUNCIÓN: Auto-incremento consecutivo factura
-- ============================================
create or replace function public.get_next_invoice_consecutive()
returns integer as $$
declare
  next_number integer;
begin
  select coalesce(max(consecutive), 0) + 1 into next_number from invoices;
  return next_number;
end;
$$ language plpgsql security definer;

-- ============================================
-- 6. ACTUALIZA get_dashboard_stats para incluir facturas
-- ============================================
create or replace function public.get_dashboard_stats()
returns json as $$
declare
  result json;
begin
  select json_build_object(
    'total_revenue', coalesce((select sum(total) from orders where status not in ('cancelado')), 0),
    'total_orders', (select count(*) from orders),
    'pending_orders', (select count(*) from orders where status = 'pendiente'),
    'total_clients', (select count(*) from profiles where role = 'client'),
    'total_appointments', (select count(*) from appointments where status in ('pendiente', 'confirmada')),
    'total_products', (select count(*) from products where status = 'activo'),
    'low_stock_products', (select count(*) from products where stock <= min_stock and stock > 0),
    'out_of_stock', (select count(*) from products where stock = 0),
    'total_invoices', (select count(*) from invoices),
    'invoices_this_month', (select count(*) from invoices where created_at >= date_trunc('month', now()))
  ) into result;
  return result;
end;
$$ language plpgsql security definer;

-- ============================================
-- 7. SEED: Configuración inicial de facturación
-- ============================================
insert into settings (key, value) values
('store_nit', '"901234567-8"'),
('store_regime', '"comun"'),
('invoice_prefix', '"FAC"'),
('invoice_resolution', '"18764000000001"'),
('invoice_resolution_date', '"2024-01-15"'),
('invoice_next_number', '1')
on conflict (key) do nothing;
