-- ============================================
-- SUPABASE SCHEMA - Valentina Niebles v2
-- Run this in Supabase SQL Editor
-- ============================================

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- ============================================
-- USERS TABLE (extends Supabase auth.users)
-- ============================================
create table profiles (
  id uuid references auth.users(id) on delete cascade primary key,
  name text not null,
  email text not null,
  phone text default '',
  role text not null default 'client' check (role in ('client', 'staff', 'manager', 'admin')),
  avatar text default '',
  wishlist int[] default '{}',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now(),
  last_login timestamp with time zone
);

-- ============================================
-- PRODUCTS TABLE
-- ============================================
create table products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique not null,
  category text not null,
  price numeric not null,
  stock int not null default 0,
  min_stock int not null default 3,
  description text default '',
  description_long text default '',
  image_url text default '',
  images text[] default '{}',
  colors text[] default '{}',
  sizes text[] default '{}',
  tags text[] default '{}',
  status text not null default 'activo' check (status in ('activo', 'inactivo', 'agotado')),
  discount numeric not null default 0,
  featured boolean not null default false,
  created_at timestamp with time zone default now(),
  views int not null default 0,
  sales int not null default 0
);

-- ============================================
-- ORDERS TABLE
-- ============================================
create table orders (
  id text primary key,
  user_id uuid references profiles(id) on delete set null,
  client_name text not null,
  client_email text not null,
  client_phone text default '',
  client_doc text default '',
  products jsonb not null,
  total numeric not null,
  status text not null default 'pendiente' check (status in ('pendiente', 'confirmado', 'en_produccion', 'enviado', 'entregado', 'cancelado')),
  payment text not null,
  address text not null,
  notes text default '',
  tracking text default '',
  carrier text default '',
  cancellation_reason text default '',
  cancellation_detail text default '',
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- ============================================
-- APPOINTMENTS TABLE
-- ============================================
create table appointments (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete set null,
  client_name text not null,
  type text not null,
  date date not null,
  time text not null,
  status text not null default 'pendiente' check (status in ('pendiente', 'confirmada', 'cancelada', 'completada')),
  notes text default '',
  created_at timestamp with time zone default now()
);

-- ============================================
-- NOTIFICATIONS TABLE
-- ============================================
create table notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade,
  type text not null,
  title text not null,
  message text not null,
  read boolean not null default false,
  link text default '',
  created_at timestamp with time zone default now()
);

-- ============================================
-- ACTIVITIES TABLE (Admin Activity Feed)
-- ============================================
create table activities (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete set null,
  type text not null,
  text text not null,
  created_at timestamp with time zone default now()
);

-- ============================================
-- SETTINGS TABLE
-- ============================================
create table settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamp with time zone default now()
);

-- ============================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================

-- Enable RLS on all tables
alter table profiles enable row level security;
alter table products enable row level security;
alter table orders enable row level security;
alter table appointments enable row level security;
alter table notifications enable row level security;
alter table activities enable row level security;
alter table settings enable row level security;

-- Helper function to check if user is admin/manager
create or replace function public.is_admin()
returns boolean as $$
  select exists (
    select 1 from profiles
    where id = auth.uid() and role in ('admin', 'manager')
  );
$$ language sql security definer;

-- Profiles: users can read their own, admins can read all
create policy "Users can view own profile"
  on profiles for select
  using (auth.uid() = id);

create policy "Admins can view all profiles"
  on profiles for select
  using (public.is_admin());

create policy "Users can update own profile"
  on profiles for update
  using (auth.uid() = id);

create policy "Users can insert own profile"
  on profiles for insert
  with check (auth.uid() = id);

-- Products: everyone can read active products, admins can manage
create policy "Anyone can view active products"
  on products for select
  using (status = 'activo' or status = 'agotado');

create policy "Admins can view all products"
  on products for select
  using (public.is_admin());

create policy "Admins can insert products"
  on products for insert
  with check (public.is_admin());

create policy "Admins can update products"
  on products for update
  using (public.is_admin());

create policy "Admins can delete products"
  on products for delete
  using (public.is_admin());

-- Orders: users can see their own, admins can see all
create policy "Users can view own orders"
  on orders for select
  using (user_id = auth.uid());

create policy "Admins can view all orders"
  on orders for select
  using (public.is_admin());

create policy "Anyone can create orders"
  on orders for insert
  with check (true);

create policy "Admins can update orders"
  on orders for update
  using (public.is_admin());

-- Appointments: users can see their own, admins can see all
create policy "Users can view own appointments"
  on appointments for select
  using (user_id = auth.uid());

create policy "Admins can view all appointments"
  on appointments for select
  using (public.is_admin());

create policy "Anyone can create appointments"
  on appointments for insert
  with check (true);

create policy "Admins can update appointments"
  on appointments for update
  using (public.is_admin());

-- Notifications: users can see their own + global (null user_id), admins can manage
create policy "Users can view own notifications"
  on notifications for select
  using (user_id = auth.uid() or user_id is null);

create policy "Admins can view all notifications"
  on notifications for select
  using (public.is_admin());

create policy "Admins can insert notifications"
  on notifications for insert
  with check (public.is_admin());

create policy "Admins can update notifications"
  on notifications for update
  using (public.is_admin());

create policy "Users can update own notifications"
  on notifications for update
  using (user_id = auth.uid());

-- Activities: admins can view all, system can insert
create policy "Admins can view activities"
  on activities for select
  using (public.is_admin());

create policy "System can insert activities"
  on activities for insert
  with check (true);

-- Settings: everyone can read, only admins can update
create policy "Anyone can view settings"
  on settings for select
  using (true);

create policy "Admins can update settings"
  on settings for all
  using (public.is_admin());

-- ============================================
-- FUNCTIONS & TRIGGERS
-- ============================================

-- Auto-create profile on signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, name, email, role, avatar)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    new.email,
    'client',
    coalesce(new.raw_user_meta_data->>'avatar_url', '')
  );
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Auto-update updated_at
create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger set_updated_at_profiles before update on profiles
  for each row execute procedure public.handle_updated_at();

create trigger set_updated_at_orders before update on orders
  for each row execute procedure public.handle_updated_at();

-- Auto-create activity on new order
create or replace function public.create_order_activity()
returns trigger as $$
begin
  insert into public.activities (user_id, type, text)
  values (
    new.user_id,
    'order',
    'Nuevo pedido ' || new.id || ' de ' || new.client_name || ' - $' || new.total
  );
  return new;
end;
$$ language plpgsql security definer;

create trigger on_order_created
  after insert on orders
  for each row execute procedure public.create_order_activity();

-- Auto-create notification on new order for admins
create or replace function public.notify_admins_new_order()
returns trigger as $$
begin
  insert into public.notifications (user_id, type, title, message, link)
  values (
    null,
    'order',
    'Nuevo pedido: ' || new.id,
    new.client_name || ' realizó un pedido por $' || new.total,
    '/admin/index.html?page=orders'
  );
  return new;
end;
$$ language plpgsql security definer;

create trigger on_order_notify_admins
  after insert on orders
  for each row execute procedure public.notify_admins_new_order();

-- Auto-create notification on new appointment
create or replace function public.notify_new_appointment()
returns trigger as $$
begin
  insert into public.notifications (user_id, type, title, message, link)
  values (
    null,
    'appointment',
    'Nueva cita agendada',
    new.client_name || ' - ' || new.type || ' el ' || new.date || ' a las ' || new.time,
    '/admin/index.html?page=appointments'
  );
  return new;
end;
$$ language plpgsql security definer;

create trigger on_appointment_notify
  after insert on appointments
  for each row execute procedure public.notify_new_appointment();

-- Auto-create notification on low stock
create or replace function public.check_low_stock()
returns trigger as $$
begin
  if new.stock <= new.min_stock and new.stock > 0 then
    insert into public.notifications (user_id, type, title, message, link)
    values (
      null,
      'stock',
      'Stock bajo: ' || new.name,
      new.name || ' tiene solo ' || new.stock || ' unidades (mínimo: ' || new.min_stock || ')',
      '/admin/index.html?page=inventory'
    );
  elsif new.stock = 0 then
    insert into public.notifications (user_id, type, title, message, link)
    values (
      null,
      'stock',
      'Producto agotado: ' || new.name,
      new.name || ' se quedó sin stock',
      '/admin/index.html?page=inventory'
    );
  end if;
  return new;
end;
$$ language plpgsql security definer;

create trigger on_stock_change
  after update on products
  for each row
  when (old.stock > new.stock)
  execute procedure public.check_low_stock();

-- Increment product sales on order
create or replace function public.increment_product_sales()
returns trigger as $$
declare
  product_record jsonb;
begin
  if new.status = 'confirmado' or new.status = 'enviado' or new.status = 'entregado' then
    for product_record in select * from jsonb_array_elements(new.products)
    loop
      update products
      set sales = sales + (product_record->>'qty')::int
      where id = (product_record->>'id')::bigint;
    end loop;
  end if;
  return new;
end;
$$ language plpgsql security definer;

create trigger on_order_status_change
  after update on orders
  for each row
  when (old.status <> new.status and new.status in ('confirmado', 'enviado', 'entregado'))
  execute procedure public.increment_product_sales();

-- ============================================
-- HELPER FUNCTIONS FOR ADMIN DASHBOARD
-- ============================================

-- Get dashboard stats
create or replace function public.get_dashboard_stats()
returns json as $$
declare
  result json;
begin
  select json_build_object(
    'total_revenue', coalesce((select sum(total) from orders where status not in ('cancelado')), 0),
    'total_orders', (select count(*) from orders),
    'pending_orders', (select count(*) from orders where status = 'pendiente'),
    'total_clients', (select count(*) from profiles where role = 'client'),
    'total_appointments', (select count(*) from appointments where status in ('pendiente', 'confirmada')),
    'total_products', (select count(*) from products where status = 'activo'),
    'low_stock_products', (select count(*) from products where stock <= min_stock and stock > 0),
    'out_of_stock', (select count(*) from products where stock = 0)
  ) into result;
  return result;
end;
$$ language plpgsql security definer;

-- Get monthly sales data
create or replace function public.get_monthly_sales(p_months int default 12)
returns table(month text, revenue numeric, order_count bigint) as $$
begin
  return query
  select
    to_char(created_at, 'Mon') as month,
    coalesce(sum(total), 0) as revenue,
    count(*) as order_count
  from orders
  where status not in ('cancelado')
    and created_at >= now() - (p_months || ' months')::interval
  group by to_char(created_at, 'Mon'), to_char(created_at, 'MM')
  order by to_char(created_at, 'MM');
end;
$$ language plpgsql security definer;

-- ============================================
-- SEED DATA
-- ============================================

-- Seed admin user (you must create this user via Supabase Auth first, then update role)
-- After creating the user in Supabase Dashboard > Authentication, run:
-- update profiles set role = 'admin' where email = 'admin@niebles.com';

-- Seed products
insert into products (name, slug, category, price, stock, min_stock, description, description_long, image_url, colors, sizes, tags, status, discount, featured) values
('Aurora', 'aurora', 'vestidos', 450000, 8, 3, 'Vestido largo en seda natural con bordados florales hechos a mano.', 'Confeccionado en seda 100% natural, este vestido largo presenta bordados florales realizados íntegramente a mano por artesanas locales.', 'img/WhatsApp%20Image%202026-05-13%20at%2011.13.18%20PM%20(3).jpeg', '{"champagne","rosa","dorado"}', '{"XS","S","M","L"}', '{"elegante","gala","seda","largo","floral","romantico","boda"}', 'activo', 0, true),
('Esmeralda', 'esmeralda', 'conjuntos', 380000, 12, 5, 'Conjunto de dos piezas con detalles dorados y corte moderno.', 'Blazer entallado con botones dorados y pantalón de corte recto.', 'img/WhatsApp%20Image%202026-05-13%20at%2011.13.18%20PM%20(2).jpeg', '{"verde","dorado","negro"}', '{"S","M","L","XL"}', '{"moderno","dorado","casual","elegante"}', 'activo', 10, true),
('Noche Eterna', 'noche-eterna', 'vestidos', 520000, 5, 3, 'Vestido de gala en tonos profundos, ideal para eventos nocturnos.', 'Vestido largo en chiffon con capas superpuestas que crean un efecto etéreo.', 'img/WhatsApp%20Image%202026-05-13%20at%2011.13.17%20PM%20(3).jpeg', '{"negro","azul marino","burdeos"}', '{"XS","S","M","L"}', '{"gala","noche","formal","sirena","elegante","fiesta"}', 'activo', 0, true),
('Real', 'real', 'blazers', 290000, 15, 5, 'Blazer estructurado con hombreras sutiles y forro de satén.', 'Blazer de corte impecable en paño de lana fría.', 'img/WhatsApp%20Image%202026-05-13%20at%2011.13.17%20PM%20(1).jpeg', '{"negro","blanco","beige"}', '{"S","M","L","XL"}', '{"formal","oficina","estructurado","power"}', 'activo', 0, false),
('Sol', 'sol', 'conjuntos', 340000, 20, 5, 'Conjunto primaveral en tonos pastel con texturas únicas.', 'Top con mangas abullonadas en organza y falda midi plisada.', 'img/WhatsApp%20Image%202026-05-13%20at%2011.13.17%20PM%20(2).jpeg', '{"rosa pastel","lavanda","crema"}', '{"XS","S","M","L"}', '{"primavera","pastel","casual","fresco","romantico"}', 'activo', 15, true),
('Luna', 'luna', 'vestidos', 480000, 2, 3, 'Vestido asimétrico con caída perfecta y detalles plateados.', 'Vestido asimétrico en crepé de seda con un hombro descubierto.', 'img/WhatsApp%20Image%202026-05-13%20at%2011.13.17%20PM%20(4).jpeg', '{"plateado","gris","azul hielo"}', '{"XS","S","M"}', '{"asimetrico","elegante","fiesta","plateado"}', 'activo', 0, true);

-- Seed settings
insert into settings (key, value) values
('store_name', '"Valentina Niebles"'),
('store_email', '"valentina@niebles.com"'),
('store_phone', '"+57 324 594 7260"'),
('store_location', '"Barranquilla, Colombia"'),
('shipping_free_min', '300000'),
('return_days', '30');
